version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=weather_archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  producer:
    build:
      context: ./producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=weather_archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root456

  consumer:
    build:
      context: ./consumer
    depends_on:
      - postgres
      - producer
    ports:
      - "8080:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=weather_archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root456
    # restart: on-failure

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
